version: '3.8'

services:
  postgres:
    image: postgres
    container_name: auth_postgres
    environment:
      POSTGRES_DB: auth_database
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
